### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by VanKouz** [hasankzl/react-flexy-table#12]
I use flexy-table to display search results from API. 
Let's say i have a count of 300 data result and i am in page 19 of 21.
If i load a fresh search result with  less count data and less max pages of above mentioned,
flexy-table stays in current page and not return to page 1 even data is loaded.
Any help/suggestion on  how i can do a reset.

**Comment by CoderSau** [comment]
Hi,

Try to use latest version of react-flexy-table. If problem doesn't solved I'm gonna upgrade a fixed version.

**Comment by VanKouz** [comment]
Hi,
thanks for the quick response.
i tried latest version; however, the problem still exists.
Please advice.
Thank you for your support

**Comment by CoderSau** [comment]
Hi, 
It's seems like when data prop change current page number and search field doesn't change. But when data prop change current page must be 1 and all filter inputs must be clear.

In the new version I try to fix that issue. Please try version 1.8.3.

Thank you for this feedback
