### ISSUE TITLE
Global search suggestion

### ISSUE THREAD

**Issue by akshat24sharma** [hasankzl/react-flexy-table#15]
Hello, I'm using this table and it's amazing, I was curious if it's possible to change the position of global search bar maybe we can attach it to some other column, like in middle or left side

**Comment by hasankzl** [comment]
hi akshat24sharma,

if you are working with version 1.8.6 or higher you can change global search position with adding this css.

```
.rft-gs-td {
    justify-content: center;
}
```

or
```

.rft-gs-td {
    justify-content: end;
}
```

this should work. 

Thanks for the feedback.
