### ISSUE TITLE
How we change the size of row

### ISSUE THREAD

**Issue by GSoulat** [hasankzl/react-flexy-table#17]
Hi, nice job for react-flexy-table

I would like to change every row, because there are to big ti height, I need --> `<td>` smaller.
![Capture](https://user-images.githubusercontent.com/75664298/131828871-fafa336f-91c5-4d0a-a72f-f2f68612f793.PNG)

How I can change ? thank you for the help

**Comment by hasankzl** [comment]
Hi GSoulat  ,

sorry for late answer.

You can see how you change table style here:
https://github.com/hasankzl/react-flexy-table#styling

for your problem you can override table style. First add a className
`
 <ReactFlexyTable data={data} className='my-table' />`

after that you can simply add css to it like

```
.my-table td {
  width:200px;
}
```

**Comment by GSoulat** [comment]
Thank you
